# Generated by Django 2.2.3 on 2019-08-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0002_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
