# Generated by Django 2.2.3 on 2019-09-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0004_auto_20190806_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
