# Generated by Django 2.2.3 on 2019-09-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0005_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantlocation',
            name='menus',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
