# Generated by Django 2.2.3 on 2019-08-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
