# Generated by Django 2.2.3 on 2019-09-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0003_auto_20190812_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
