# Generated by Django 3.0.2 on 2020-01-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0005_fooditem_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='group',
            new_name='category',
        ),
    ]
